# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('descrizione', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OggAsta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('data', models.DateTimeField()),
                ('scadenza', models.DateTimeField()),
                ('descrizione', models.CharField(max_length=50)),
            ],
        ),
    ]
