# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestione_catalogo', '0001_initial'),
        ('gestione_acquisti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntata',
            name='idasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione_catalogo.OggAsta'),
        ),
    ]
