# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestione_acquisti', '0003_puntata_vincente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntata',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='puntata',
            name='idasta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestione_catalogo.OggAsta'),
        ),
        migrations.AlterField(
            model_name='puntata',
            name='importo',
            field=models.IntegerField(default=0.01),
        ),
        migrations.AlterField(
            model_name='puntata',
            name='vincente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
